### ISSUE TITLE
So much chrome processes

### ISSUE THREAD

**Issue by italojs** [blackcapz/spammer#13]
I note that any browser is closed after the spammer-core do the job, it's causing a SUPER memory consume.
Here is some images from my machine screen

_memory_
![image](https://user-images.githubusercontent.com/9022134/51987238-21efe480-2489-11e9-947a-6e22a96c6c0a.png)

_processes_
![image](https://user-images.githubusercontent.com/9022134/51987264-33d18780-2489-11e9-97b4-44486a0eee47.png)

obs: I can't add blob link here -  `[]()`

**Comment by IgorHalfeld** [comment]
Hmm.. You can simple copy and paste imagens here, github include `[]()` by uploading them

_When uploading_
![image](https://user-images.githubusercontent.com/9022134/51987272-3cc25900-2489-11e9-9451-6262e4af152f.png)

_After_
![image](https://user-images.githubusercontent.com/9022134/51987297-4ea3fc00-2489-11e9-8b31-cd8c38810379.png)

**Comment by IgorHalfeld** [comment]
The puppeteer instances limit should be defined on the spammer instance by some config
